# Generated by Django 3.2.7 on 2021-09-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210916_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='git2',
        ),
    ]
