# Generated by Django 3.2.7 on 2021-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_git2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_update',
            field=models.CharField(default='', max_length=100),
        ),
    ]
