# Generated by Django 3.2.7 on 2021-09-17 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
