# Generated by Django 3.2.7 on 2021-09-17 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
