# Generated by Django 3.2.7 on 2021-09-17 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_update',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
