# Generated by Django 3.2.7 on 2021-09-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_update',
        ),
    ]
