# Generated by Django 3.2.7 on 2021-09-17 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_profile_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_update',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
